# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pT_Q7Cga3touEwAgBoCwqWL0M87a58Og
"""

#from google.colab import files
#a=files.upload()

import pandas as pd
from sklearn.tree import DecisionTreeRegressor
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv("Project4.csv")
data

x=data.iloc[:,1].values
x=x.reshape(-1,1)

y=data.iloc[:,2].values
y=y.reshape(-1,1)

reg=DecisionTreeRegressor(random_state=0)
reg.fit(x,y)

pred_y=reg.predict(x)

x_grid=np.arange(min(x),max(x),0.01)
x_grid=x_grid.reshape(len(x_grid),1)
plt.scatter(x,y,color='red')
plt.plot(x_grid,reg.predict(x_grid),color="blue")
plt.xlabel("Level")
plt.ylabel("Salary")
plt.title("Salary prediction Using Decision Tree algo")
plt.show()



