# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pT_Q7Cga3touEwAgBoCwqWL0M87a58Og
"""

#Prediction Using Polynomial Regression Algorhithim

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

data=pd.read_csv("Project2.csv")

x=data.iloc[:,1].values

y=data.iloc[:,2].values

x=x.reshape(-1,1)
y=y.reshape(-1,1)

poly=PolynomialFeatures(degree=4)
x_poly=poly.fit_transform(x)
poly.fit(x_poly,y)

le=LinearRegression()
le.fit(x_poly,y)

pred_y=le.predict(x_poly)

plt.scatter(x,y,color="red")
plt.plot(x_poly,le.predict(x_poly),color="green")
plt.xlabel("Level of Postion")
plt.ylabel("Salary according to level")
plt.title("Salary vs Level plot")
plt.show()