# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pT_Q7Cga3touEwAgBoCwqWL0M87a58Og
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
import matplotlib.pyplot as plt
import numpy as np

data=pd.read_csv("Project3.csv")
data.head(5)

x=data.iloc[:,1].values
x=x.reshape(-1,1)

y=data.iloc[:,2].values
y=y.reshape(-1,1)

sc_x=StandardScaler()
sc_y=StandardScaler()
x=sc_x.fit_transform(x)
y=sc_y.fit_transform(y)

reg=SVR(kernel='rbf')
reg.fit(x,y)

plt.scatter(x,y,color='red')
plt.plot(x,reg.predict(x),color='blue')
plt.xlabel("Level")
plt.ylabel("Salary")
plt.title("Salary prediction using SVR Algo")
plt.show()

#applying inverse transform to predict a float type input e.g:- 6.5,7.5 etc.
sc_x_val=sc_x.transform(np.array([[6.5]]))
sc_y_pred=reg.predict(sc_x_val)
final_pred=sc_y.inverse_transform(sc_y_pred)
print(final_pred)
#for importing files on google colab
#from google.colab import files
#a=files.upload()
